user  nginx;
worker_processes  1;
include /etc/nginx/modules-enabled/*.conf;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;
events {
  worker_connections  1024;
}
http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;
  log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log  /var/log/nginx/access.log  main;
  sendfile        on;
  keepalive_timeout  65;

  server {
    listen $DOCKER_APP_PORT ssl http2;
    server_name webclientrtustage.satel.org;
    root /usr/share/nginx/html/;
    index index.html;
    client_max_body_size 50M;

    ssl_certificate /usr/share/nginx/ssl/chat.pem;
    ssl_certificate_key /usr/share/nginx/ssl/key.pem;
    error_page 497 301 =307 https://$host:$server_port$request_uri;

    location /api/ {
      proxy_pass http://127.0.0.1:6001/api/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_http_version 1.1;
      proxy_read_timeout 360s;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location = /im {
      rewrite ^/im/(.*) /$1 break;
      rewrite_log on;
      proxy_pass http://127.0.0.1:8145;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_http_version 1.1;
      proxy_read_timeout 360s;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location = /sip {
      rewrite ^/sip/(.*) /$1 break;
      rewrite_log on;
      proxy_pass http://127.0.0.1:5059;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Satel-Server-Addr $server_addr;
      proxy_http_version 1.1;
      proxy_read_timeout 360s;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /prompt/ {
      proxy_pass http://127.0.0.1:8441/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      proxy_http_version 1.1;
      proxy_read_timeout 360s;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location /selector/ {
      proxy_pass http://127.0.0.1:8441/call_records/selector/;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_http_version 1.1;
      proxy_read_timeout 360s;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # Отдаем статические файлы
    location ~* \.(js|css|png|jpg|jpeg|gif|svg|woff|woff2)$ {
      try_files $uri =404;
    }

    # Обрабатываем SPA-маршрутизацию, отдавая index.html
    location / {
      expires -1;
      try_files $uri $uri/ /index.html;
    }

    error_page 400 401 402 403 404 500 501 502 503 504 /errors/errors.html;

    location /errors/errors.html {
      root /usr/share/nginx/html;
      sub_filter '$status' $status;
      sub_filter '$status_text' $status_text;
      sub_filter_once on;
    }

    location /errors/ {
      internal;
      root /usr/share/nginx/html;
    }
  }
  map $status $status_text {
     400 "Bad Request";
     401 "Unauthorized";
     402 "Payment Required";
     403 "Forbidden";
     404 "Not Found";
     500 "Internal Server Error";
     501 "Not Implemented";
     502 "Bad Gateway";
     503 "Service Unavailable";
     504 "Gateway Timeout";
     default "Unknown Error";
  }
}
